services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "clickhouse://default:@clickhouse:8123/default"
      REDIS_HOST: "redis_cache"
      REDIS_PORT: "6379"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8
    depends_on:
      - clickhouse
      - redis
      - rabbitmq

  redis:
    image: "redis:latest"
    container_name: "redis_cache"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A app.celery_app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis_cache:6379/0
      - PYTHONPATH=/app
    depends_on:
      - redis
      - postgres
  celery-beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app

volumes:
  clickhouse_data:
  postgres_data:
