version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse  # Хранение данных ClickHouse в томе

  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "clickhouse://default:@clickhouse:8123/default"
    depends_on:
      - clickhouse

  redis:
    image: "redis:latest"
    container_name: "redis_cache"
    ports:
      - "6379:6379"

volumes:
  clickhouse_data:  # Тома данных ClickHouse
